// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4970.IceCubed2017.commands;
import edu.wpi.first.wpilibj.command.CommandGroup;

import org.usfirst.frc4970.IceCubed2017.Robot;

/**
 *
 */
public class PlaceGear extends CommandGroup {
    public PlaceGear() {
 //   	addParallel(new HoldGear(Robot.grabDutyCycle));
    	addSequential(new TimedDrive(Robot.timedDriveTimeout, Robot.timedDriveDutyCycle));
//    	addSequential(new TimedTurn(Robot.timedTurnTimeout, Robot.timedTurnRate));
 //   	addSequential(new DriveTowardTower(Robot.towerDriveDutyCycle));
//    	addSequential(new ReleaseGear(Robot.releaseGearTimeout, Robot.releaseDutyCycle));
    }
}