// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4970.IceCubed2017.commands;
import edu.wpi.first.wpilibj.command.CommandGroup;

import org.usfirst.frc4970.IceCubed2017.Robot;

/**
 *
 */
public class PlaceGearGamble extends CommandGroup {
    public PlaceGearGamble() {
    	
    	addParallel(new HoldGear(Robot.grabDutyCycle));

    	// in center position, use the shorter timed drive
       	addSequential(new TimedDrive(Robot.CENTER));    		
    	
    	// attempt to find the target and set a gyro heading
    	addSequential(new DriveTowardTower());

   		// if no target is found, then drive straight
   		addSequential(new TimedDriveAuto(false));   		
    	
    	addSequential(new ReleaseGear(0.5, true));
   		addSequential(new LiftTray(true, true));
   		addSequential(new ReverseDrive(true));
    }
}