// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4970.IceCubed2017.commands;
import edu.wpi.first.wpilibj.command.CommandGroup;

import org.usfirst.frc4970.IceCubed2017.Robot;

/**
 *
 */
public class PlaceGear extends CommandGroup {
    public PlaceGear(double turnDegrees) {
    	addParallel(new HoldGear(Robot.grabDutyCycle));
    	if (turnDegrees != 0.0)
    	{
    		// not in center position, use the longer timed drive
        	addSequential(new TimedDrive(false));
    		addSequential(new TurnDegrees(turnDegrees));
    	} else
    	{
    		// in center position, use the shorter timed drive
        	addSequential(new TimedDrive(true));    		
    	}
    	addSequential(new DriveTowardTower());

    	addSequential(new ReleaseGear(0.5));
   		addSequential(new LiftTray(true));
   		addSequential(new ReverseDrive());
    	addSequential(new TimedDriveAuto(false));   		
    }
}